server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    user:
      name: rishabh
      password: 1234
      roles:
        - ADMIN

project:
  image: images/

logging:
  level:
    org:
      springframework:
        security: DEBUG

